"""Add follow relationship and bookmark methods

Revision ID: a79001f89a5b
Revises: 07cc6ebe3e04
Create Date: 2021-11-13 15:55:14.895312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a79001f89a5b'
down_revision = '07cc6ebe3e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('following_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_followers_follower_id_users')),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name=op.f('fk_followers_following_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
